name: "Lazy Action Python"
description: "Github action to perform build, test , scan and generate image."
inputs:
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: false
    default: "."
  ecr_repository:
    description: "ECR repository name"
    required: true
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: true
    default: "true"
  test_framework:
    description: "Framework for Tests"
    required: false
    default: "pytest"
  github_token:
    description: "Github token"
    required: true
runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/python-action:1.3.0
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
