name: "Lazy Action Python"
description: "Github action to perform build, test , scan and generate image."
inputs:
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: true
  ecr_repository:
    description: "Ecr repository name"
    required: true
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: true
    default: "true"
runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/python-action:latest