---
# yamllint disable rule:line-length
name: Actions Python
description: >
  Github action to perform build, test , scan and generate image.
inputs:
  dockerfile_dir_path:
    description: Directory path to the dockerfile
    required: false
    default: .
  ecr_repository:
    description: ECR repository name
    required: true
  container_push_enabled:
    description: Enable Build and Push Container Image
    required: true
    default: 'true'
  python-version:
    description: >
      The python-version input is optional.
      If not supplied, the action will try to resolve the
      version from the default `.python-version` file.
      If the `.python-version` file doesn't exist Python or PyPy
      version from the PATH will be used.
      The default version of Python or PyPy in PATH varies
      between runners and can be changed unexpectedly
      so we recommend always setting Python version explicitly
      using the python-version or python-version-file inputs.
    required: false
runs:
  using: composite
  steps:
    - name: Setup Actions
      uses: variant-inc/actions-setup@v2

    - name: Sonar Setup
      id: sonar-setup
      uses: variant-inc/actions-collection/sonar-setup@v2

    - name: Get Action ref
      id: action-ref
      shell: bash
      run: |
        mkdir -p ./.github/workflows/actions-python/test
        cp -R ${{ github.action_path }}/test/* ./.github/workflows/actions-python/test/

    - name: Build & Test Python
      uses: ./.github/workflows/actions-python/test
      if: ${{ steps.sonar-setup.outputs.sonar_skip != 'True' }}
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build and Push Image
      uses: variant-inc/actions-collection/build-push-image@v2
      if: ${{ inputs.container_push_enabled == 'true' }}
      with:
        dockerfile_dir_path: ${{ inputs.dockerfile_dir_path }}
        ecr_repository: ${{ inputs.ecr_repository }}
