name: "Lazy Action Python"
description: "Github action to perform build, test , scan and generate image."
inputs:
  src_file_dir_path:
    description: "Directory path to the solution file"
    required: true
    default: "."
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: true
  ecr_repository:
    description: "Ecr repository name"
    required: true
  sonar_scan_in_docker:
    description: "Is sonar scan running as part of Dockerfile?"
    required: false
    default: "false"
  sonar_scan_in_docker_target:
    description: "sonar scan in docker target"
    required: false
    default: "sonarscan-env"
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: false
    default: "true"
runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/dotnet-action:v1.1.3
  env:
    GITHUB_TOKEN: ${{ inputs.nuget_pull_token }}