name: "Lazy Action Python"
description: "Github action to perform build, test , scan and generate image."
inputs:
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: false
    default: "."
  ecr_repository:
    description: "ECR repository name"
    required: true
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: true
    default: "true"
  test_framework:
    description: "Framework for Tests"
    required: false
    default: "pytest"
  multirepo_mode:
    description: "Instead of following default execution path, use the multirepo mode"
    required: false
    default: "false"
  multirepo_scan_path:
    description: "Path to the directory where lambda dirs are located, used for multirepo mode"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile" #image: docker://public.ecr.aws/p4v7w0a5/lazy/python-action:v1.2.0
